# Generated by Django 6.0.5 on 2026-05-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_district_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_location_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.district_model')),
            ],
            options={
                'db_table': 'branch_location',
            },
        ),
        migrations.CreateModel(
            name='machinery_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('specific', models.CharField(max_length=150)),
                ('base_price_day', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateField()),
                ('gst', models.CharField(max_length=20)),
                ('img_url1', models.CharField(max_length=100)),
                ('img_url2', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.branch_location_model')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category_model')),
            ],
            options={
                'db_table': 'machinery',
            },
        ),
        migrations.CreateModel(
            name='insure_policy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=30)),
                ('policy_no', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_detail', models.CharField(max_length=150)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.machinery_model')),
            ],
            options={
                'db_table': 'insure_policy',
            },
        ),
        migrations.CreateModel(
            name='maintenance_log_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=150)),
                ('service_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('next_due_date', models.DateField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.machinery_model')),
            ],
            options={
                'db_table': 'maintenance_logs',
            },
        ),
    ]
